export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY'
export const GET_FAVOURITE_PRODUCT = 'GET_FAVOURITE_PRODUCT'
export const POST_FAVOURITE_PRODUCT = 'POST_FAVOURITE_PRODUCT'
export const DELETE_FAVOURITE_PRODUCT = 'DELETE_FAVOURITE_PRODUCT'
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT'
export const GET_ALL_LIST_PRODUCT = 'GET_ALL_LIST_PRODUCT'
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const GET_CATEGORY_SLUG = 'GET_CATEGORY_SLUG'
export const GET_CATEGORY_DETAIL = 'GET_CATEGORY_DETAIL'
export const GET_PRODUCT_BEST_SELLER = 'GET_PRODUCT_BEST_SELLER'
export const GET_PRODUCT_FROM_GIGA_DIGITAL = 'GET_PRODUCT_FROM_GIGA_DIGITAL'

export const GET_CAROUSEL = 'GET_CAROUSEL'
export const GET_PRODUCT_HOME = 'GET_PRODUCT_HOME'
export const GET_FLASH_SALE = 'GET_FLASH_SALE'
export const GET_BRAND = 'GET_BRAND'

// Comment
export const GET_COMMENT_PRODUCT = 'GET_COMMENT_PRODUCT'
export const POST_COMMENT_PRODUCT = 'POST_COMMENT_PRODUCT'
export const PUT_COMMENT_PRODUCT = 'PUT_COMMENT_PRODUCT'
export const GET_SALE_OFF = 'GET_SALE_OFF'

// Order
export const GET_CART = 'GET_CART'
export const COUNT_CART = 'COUNT_CART'
export const POST_CART = 'POST_CART'
export const PUT_CART = 'PUT_CART'
export const DELETE_CART = 'DELETE_CART'

export const CREATE_ORDER = 'CREATE_ORDER'
export const CONFIRM_ORDER = 'CONFIRM_ORDER'
export const GET_LIST_ORDER = 'GET_LIST_ORDER'
export const GET_DETAIL_ORDER = 'GET_DETAIL_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'

export const GET_BAO_HANH = 'GET_BAO_HANH'
export const GET_CHECK_ORDER = 'GET_CHECK_ORDER'

// profile
export const GET_CITY = 'GET_CITY'
export const GET_DISTRICT = 'GET_DISTRICT'
export const GET_PROFILE = 'GET_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'

// news
export const GET_CATEGORY_NEWS = 'GET_CATEGORY_NEWS'
export const GET_SUB_CATEGORY_NEWS = 'GET_SUB_CATEGORY_NEWS'
export const GET_NEW_BY_CATE = 'GET_NEW_BY_CATE'
export const GET_NEW_BY_SLUG = 'GET_NEW_BY_SLUG'
export const GET_NEW_BY_HOME = 'GET_NEW_BY_HOME'
export const GET_NEW_BY_CREATED_AT = 'GET_NEW_BY_CREATED_AT'
export const GET_NEW_BY_TAG = 'GET_NEW_BY_TAG'

export const CLEAR_DATA = 'CLEAR_DATA'
export const CLEAR_LIST_PRODUCT = 'CLEAR_LIST_PRODUCT'